# N.B. This file is bundled and distributed in the enterprise docker image.
# It should not contain any secrets. Test the image if you change it!
app:
  build_buddy_url: "http://localhost:8080"
  events_api_url: "grpc://localhost:1985"
  cache_api_url: "grpc://localhost:1985"
database:
  data_source: "sqlite3:///buildbuddy/buildbuddy.db"
storage:
  ttl_seconds: 0  # No TTL (yet).
  chunk_file_size_bytes: 3000000  # 3 MB
  disk:
    root_directory: "/buildbuddy/blobs/"
cache:
  disk:
    root_directory: "/buildbuddy/cache/"
  max_size_bytes: 10000000000  # 10 GB
