executor:
  root_directory: "/tmp/remote_build"
  docker_socket: /var/run/docker.sock
  docker_inherit_user_ids: true
  app_target: "grpc://localhost:1985"
  local_cache_directory: "/tmp/filecache"
  local_cache_size_bytes: 1000000000 # 1GB
